import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { join, sep } from "node:path";
import { tmpdir } from "node:os";
import { isIgnored, parseIgnoreRule } from "../src/ignore.js";
import { scan } from "../src/scanner.js";
import { buildGraph } from "../src/graph.js";
import { buildSkelograph } from "../src/index.js";
import { installClaude } from "../src/claude.js";
import { detectWorkspace } from "../src/workspace.js";

async function makeTmp(name: string): Promise<string> {
  return mkdtemp(join(tmpdir(), `skelograph-${name}-`));
}

test("ignore rules match directories and globs", () => {
  const rules = [parseIgnoreRule("node_modules/"), parseIgnoreRule("*.generated.ts")];
  assert.equal(isIgnored(rules, "node_modules", true), true);
  assert.equal(isIgnored(rules, "pkg/node_modules", true), true);
  assert.equal(isIgnored(rules, "src/foo.generated.ts", false), true);
  assert.equal(isIgnored(rules, "src/foo.ts", false), false);
});

test("scan respects .gitignore and skips generated files", async () => {
  const root = await makeTmp("scan");
  try {
    await mkdir(join(root, "src"));
    await writeFile(join(root, ".gitignore"), "src/ignored.ts\n", "utf8");
    await writeFile(join(root, "src", "index.ts"), "export function run() {}\n", "utf8");
    await writeFile(join(root, "src", "ignored.ts"), "export function nope() {}\n", "utf8");
    await writeFile(
      join(root, "src", "generated.ts"),
      "// @generated by build\nexport const x = 1;\n",
      "utf8",
    );
    await writeFile(join(root, ".env"), "TOKEN=secret\n", "utf8");
    await writeFile(join(root, "package.json"), JSON.stringify({ name: "demo" }), "utf8");

    const result = await scan(root);
    const paths = result.files.map((f) => f.relativePath).sort();
    assert.deepEqual(paths, ["src/index.ts"]);
    assert.equal(result.stats.skippedSensitive, 1);
    assert.equal(result.stats.skippedGenerated, 1);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test("workspace detection parses pnpm-workspace.yaml", async () => {
  const root = await makeTmp("pnpm");
  try {
    await writeFile(
      join(root, "package.json"),
      JSON.stringify({ name: "monorepo", private: true }),
      "utf8",
    );
    await writeFile(
      join(root, "pnpm-workspace.yaml"),
      "packages:\n  - 'apps/*'\n  - 'packages/*'\n",
      "utf8",
    );
    await mkdir(join(root, "apps", "web"), { recursive: true });
    await writeFile(
      join(root, "apps", "web", "package.json"),
      JSON.stringify({ name: "@acme/web", description: "Web app", dependencies: { "@sveltejs/kit": "^2" } }),
      "utf8",
    );
    await mkdir(join(root, "packages", "auth"), { recursive: true });
    await writeFile(
      join(root, "packages", "auth", "package.json"),
      JSON.stringify({ name: "@acme/auth", description: "Auth helpers" }),
      "utf8",
    );

    const ws = await detectWorkspace(root);
    assert.equal(ws.kind, "pnpm");
    const names = ws.packages.map((p) => p.name).sort();
    assert.deepEqual(names, ["@acme/auth", "@acme/web"]);
    const web = ws.packages.find((p) => p.name === "@acme/web");
    assert.equal(web?.framework, "sveltekit");
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test("graph extracts exports, JSDoc, and cross-file imports", async () => {
  const root = await makeTmp("graph");
  try {
    await writeFile(join(root, "package.json"), JSON.stringify({ name: "demo" }), "utf8");
    await mkdir(join(root, "src"));
    await writeFile(
      join(root, "src", "util.ts"),
      "/** Helper that returns one. */\nexport function helper() { return 1; }\nfunction privateThing() {}\n",
      "utf8",
    );
    await writeFile(
      join(root, "src", "index.ts"),
      "import { helper } from './util';\nexport const run = () => helper();\n",
      "utf8",
    );

    const graph = buildGraph(await scan(root));
    const utilSymbols = graph.fileSymbols["src/util.ts"] ?? [];
    const helper = utilSymbols.find((s) => s.name === "helper");
    assert.ok(helper);
    assert.equal(helper?.visibility, "public");
    assert.match(helper?.doc ?? "", /Helper that returns one/);
    const privateSymbol = utilSymbols.find((s) => s.name === "privateThing");
    assert.equal(privateSymbol?.visibility, "private");

    assert.ok(graph.symbolIndex["helper"]);
    assert.equal(graph.symbolIndex["helper"], "src/util.ts");

    const importEdge = graph.edges.find(
      (edge) => edge.source === "file:src/index.ts" && edge.target === "file:src/util.ts",
    );
    assert.ok(importEdge);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test("flow inference produces all six required sections for a SvelteKit endpoint", async () => {
  const root = await makeTmp("flow");
  try {
    await writeFile(join(root, "package.json"), JSON.stringify({ name: "demo", dependencies: { "@sveltejs/kit": "^2" } }), "utf8");
    await mkdir(join(root, "src", "routes", "checkout"), { recursive: true });
    await mkdir(join(root, "src", "lib"), { recursive: true });
    await writeFile(
      join(root, "src", "lib", "auth.ts"),
      "/** Verify session cookie. */\nexport function verifySession(token: string) { if (!token) throw new Error('no token'); }\n",
      "utf8",
    );
    await writeFile(
      join(root, "src", "lib", "orders.ts"),
      "/** Create an order. */\nexport function createOrder(cart: unknown) { return { id: 1 }; }\n",
      "utf8",
    );
    await writeFile(
      join(root, "src", "routes", "checkout", "+server.ts"),
      [
        "import { verifySession } from '../../lib/auth';",
        "import { createOrder } from '../../lib/orders';",
        "export async function POST({ request }: { request: Request }) {",
        "  const body = await request.json();",
        "  if (!body.cart) return new Response('bad', { status: 400 });",
        "  verifySession(body.token);",
        "  try {",
        "    const order = createOrder(body.cart);",
        "    return new Response(JSON.stringify(order), { status: 200 });",
        "  } catch (e) {",
        "    return new Response('error', { status: 500 });",
        "  }",
        "}",
        "",
      ].join("\n"),
      "utf8",
    );

    const graph = buildGraph(await scan(root));
    assert.ok(graph.flows.length >= 1);
    const flow = graph.flows[0];

    assert.match(flow.trigger, /POST/);
    assert.ok(flow.preconditions.length > 0);
    assert.ok(flow.steps.length >= 2);
    assert.ok(flow.decisionPoints.some((d) => /400/.test(d.description)));
    assert.ok(flow.failurePaths.length > 0);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test("buildSkelograph writes .claude/ structure and preserves user-edited flow notes", async () => {
  const root = await makeTmp("build");
  try {
    await writeFile(join(root, "package.json"), JSON.stringify({ name: "demo", dependencies: { "@sveltejs/kit": "^2" } }), "utf8");
    await mkdir(join(root, "src", "routes", "hello"), { recursive: true });
    await writeFile(
      join(root, "src", "routes", "hello", "+server.ts"),
      "export function GET() { return new Response('hi'); }\n",
      "utf8",
    );

    const first = await buildSkelograph({ root });
    assert.ok(first.written.some((p) => p.endsWith("INDEX.md")));
    assert.ok(first.written.some((p) => p.endsWith("MAP.json")));
    assert.ok(first.written.some((p) => p.endsWith("manifest.json")));

    const indexContent = await readFile(join(root, ".claude", "INDEX.md"), "utf8");
    assert.match(indexContent, /## Where to Look/);

    const claudeMd = await readFile(join(root, "CLAUDE.md"), "utf8");
    assert.match(claudeMd, /HARD RULES/);
    assert.match(claudeMd, /ALWAYS:/);
    assert.match(claudeMd, /NEVER:/);

    const flowFiles = first.written.filter((p) => p.includes(`${join(".claude", "FLOWS")}${sep}`));
    assert.ok(flowFiles.length > 0);
    const flowPath = flowFiles[0];
    const flowContent = await readFile(flowPath, "utf8");
    assert.match(flowContent, /generated: true/);

    const customized = flowContent.replace(
      /<!-- user-notes:start -->[\s\S]*?<!-- user-notes:end -->/,
      "<!-- user-notes:start -->\nCUSTOM USER NOTE\n<!-- user-notes:end -->",
    );
    await writeFile(flowPath, customized, "utf8");

    const second = await buildSkelograph({ root });
    const afterContent = await readFile(flowPath, "utf8");
    assert.match(afterContent, /CUSTOM USER NOTE/);
    void second;

    const pinned = afterContent.replace("generated: true", "generated: false");
    await writeFile(flowPath, pinned, "utf8");
    await buildSkelograph({ root });
    const stillPinned = await readFile(flowPath, "utf8");
    assert.match(stillPinned, /generated: false/);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test("cargo workspace detection + Rust extraction", async () => {
  const root = await makeTmp("cargo");
  try {
    await writeFile(
      join(root, "Cargo.toml"),
      [
        "[workspace]",
        "members = [",
        "    \"crates/kernel\",",
        "    \"crates/shop_api\",",
        "]",
        "resolver = \"2\"",
        "",
        "[workspace.package]",
        "edition = \"2024\"",
        "",
      ].join("\n"),
      "utf8",
    );

    await mkdir(join(root, "crates", "kernel", "src"), { recursive: true });
    await writeFile(
      join(root, "crates", "kernel", "Cargo.toml"),
      [
        "[package]",
        "name = \"kernel\"",
        "description = \"Shared app config and error envelope.\"",
        "version.workspace = true",
        "",
        "[dependencies]",
        "anyhow = \"1.0\"",
        "",
      ].join("\n"),
      "utf8",
    );
    await writeFile(
      join(root, "crates", "kernel", "src", "lib.rs"),
      [
        "//! Core kernel types shared across every API surface.",
        "",
        "/// Runtime configuration parsed from the environment.",
        "pub struct AppConfig {",
        "    pub port: u16,",
        "}",
        "",
        "fn helper() {}",
        "",
      ].join("\n"),
      "utf8",
    );

    await mkdir(join(root, "crates", "shop_api", "src"), { recursive: true });
    await writeFile(
      join(root, "crates", "shop_api", "Cargo.toml"),
      [
        "[package]",
        "name = \"shop_api\"",
        "",
        "[[bin]]",
        "name = \"shop_api\"",
        "path = \"src/main.rs\"",
        "",
        "[dependencies]",
        "axum = { version = \"0.8\" }",
        "kernel = { path = \"../kernel\" }",
        "",
      ].join("\n"),
      "utf8",
    );
    await writeFile(
      join(root, "crates", "shop_api", "src", "main.rs"),
      [
        "//! Shop API binary.",
        "",
        "use axum::{Router, routing::{get, post}};",
        "use kernel::AppConfig;",
        "",
        "#[tokio::main]",
        "async fn main() -> anyhow::Result<()> {",
        "    let app = Router::new()",
        "        .route(\"/health\", get(health))",
        "        .route(\"/v1/auth/login\", post(login));",
        "    let _ = (app, AppConfig { port: 8080 });",
        "    Ok(())",
        "}",
        "",
        "async fn health() -> &'static str { \"ok\" }",
        "",
        "#[utoipa::path(post, path = \"/v1/auth/login\", tag = \"shop\",",
        "    request_body = LoginRequest,",
        "    responses((status = 200, description = \"Session issued\", body = LoginResponse),",
        "        (status = 409, description = \"Already exists\")))]",
        "async fn login() -> axum::http::StatusCode {",
        "    let app = kernel::Authenticator::new();",
        "    app.authenticate();",
        "    if false { return axum::http::StatusCode::BAD_REQUEST; }",
        "    axum::http::StatusCode::OK",
        "}",
        "",
      ].join("\n"),
      "utf8",
    );

    await writeFile(
      join(root, "crates", "kernel", "src", "auth.rs"),
      [
        "//! Kernel auth glue.",
        "",
        "pub struct Authenticator {",
        "    pub version: u8,",
        "}",
        "",
        "impl Authenticator {",
        "    /// Construct a new authenticator.",
        "    pub fn new() -> Self { Self { version: 1 } }",
        "",
        "    /// Run authentication, returning AppError::Unauthorized on failure.",
        "    pub fn authenticate(&self) -> Result<(), AppError> {",
        "        if self.version == 0 {",
        "            return Err(AppError::Unauthorized);",
        "        }",
        "        Ok(())",
        "    }",
        "}",
        "",
        "pub enum AppError {",
        "    Unauthorized,",
        "    NotFound,",
        "}",
        "",
      ].join("\n"),
      "utf8",
    );

    const graph = buildGraph(await scan(root));

    assert.equal(graph.workspace.kind, "cargo");
    const names = graph.workspace.packages.map((p) => p.name).sort();
    assert.deepEqual(names, ["kernel", "shop_api"]);

    const kernel = graph.workspace.packages.find((p) => p.name === "kernel");
    assert.equal(kernel?.description, "Shared app config and error envelope.");

    const kernelSymbols = graph.fileSymbols["crates/kernel/src/lib.rs"] ?? [];
    const appConfig = kernelSymbols.find((s) => s.name === "AppConfig");
    assert.equal(appConfig?.visibility, "public");
    assert.match(appConfig?.doc ?? "", /Runtime configuration/);
    const helper = kernelSymbols.find((s) => s.name === "helper");
    assert.equal(helper?.visibility, "private");

    assert.ok(graph.entryPoints.some((e) => e.kind === "rust-main"));
    const routes = graph.entryPoints.filter((e) => e.kind === "axum-route");
    assert.equal(routes.length, 2);
    assert.ok(routes.some((r) => r.httpMethod === "GET" && r.routePath === "/health"));
    assert.ok(routes.some((r) => r.httpMethod === "POST" && r.routePath === "/v1/auth/login"));

    const loginFlow = graph.flows.find((f) => f.entry.routePath === "/v1/auth/login");
    assert.ok(loginFlow, "login flow must be generated");
    assert.ok(loginFlow!.steps.some((s) => s.symbol === "login"));
    assert.ok(loginFlow!.decisionPoints.some((d) => /400/.test(d.description)));

    // v1.2: utoipa responses become declarative decision points.
    assert.ok(
      loginFlow!.decisionPoints.some((d) => /utoipa.*200/.test(d.description) && /Session issued/.test(d.description)),
      "utoipa 200 response should appear as a decision point",
    );
    assert.ok(
      loginFlow!.decisionPoints.some((d) => /utoipa.*409/.test(d.description)),
      "utoipa 409 response should appear as a decision point",
    );
    assert.ok(
      loginFlow!.decisionPoints.some((d) => /Request body type.*LoginRequest/.test(d.description)),
      "utoipa request body should be surfaced",
    );

    // v1.2: impl blocks qualify method symbols as Type::method.
    const kernelAuth = graph.fileSymbols["crates/kernel/src/auth.rs"] ?? [];
    const implMethod = kernelAuth.find((s) => s.name === "Authenticator::authenticate");
    assert.ok(implMethod, "impl method should be qualified as Authenticator::authenticate");
    assert.equal(implMethod?.visibility, "public");

    // MAP.json should index the qualified method.
    assert.ok(graph.symbolIndex["Authenticator::authenticate"], "MAP.json should include Authenticator::authenticate");

    // v1.2: 1-hop method resolution surfaces the authenticate() call as a step.
    assert.ok(
      loginFlow!.steps.some((s) => s.filePath === "crates/kernel/src/auth.rs"),
      "login flow should trace authenticate() call across crates to kernel/src/auth.rs",
    );

    // v1.2: AppError::Unauthorized variant should map to 401.
    const authenticateFlow = graph.flows.find((f) => f.entry.kind === "axum-route");
    assert.ok(authenticateFlow);
    // authenticate is on the kernel side; the login flow pulls its decision points via scoping.
    assert.ok(
      loginFlow!.decisionPoints.some((d) => /AppError::Unauthorized/.test(d.description) && /401/.test(d.description)),
      "AppError::Unauthorized should map to HTTP 401 in the flow that traces to it",
    );
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test("kotlin extractor surfaces composables, types, and resolves jvm imports", async () => {
  const root = await makeTmp("kotlin");
  try {
    await writeFile(join(root, "package.json"), JSON.stringify({ name: "android-demo" }), "utf8");
    await mkdir(join(root, "app", "ui"), { recursive: true });
    await mkdir(join(root, "app", "data"), { recursive: true });
    await writeFile(
      join(root, "app", "ui", "MainScreen.kt"),
      [
        "package com.app.ui",
        "",
        "import com.app.data.User",
        "",
        "@Composable",
        "fun MainScreen(user: User) {",
        "  println(user)",
        "}",
        "",
        "data class HeaderState(val title: String)",
        "",
        "object Theme",
        "",
      ].join("\n"),
      "utf8",
    );
    await writeFile(
      join(root, "app", "data", "User.kt"),
      ["package com.app.data", "", "data class User(val name: String)", ""].join("\n"),
      "utf8",
    );

    const graph = buildGraph(await scan(root));
    const screenSymbols = graph.fileSymbols["app/ui/MainScreen.kt"] ?? [];
    const main = screenSymbols.find((s) => s.name === "MainScreen");
    assert.ok(main, "expected MainScreen symbol");
    assert.equal(main?.kind, "function");
    assert.match(main?.doc ?? "", /Composable/);

    const header = screenSymbols.find((s) => s.name === "HeaderState");
    assert.equal(header?.kind, "class");

    const theme = screenSymbols.find((s) => s.name === "Theme");
    assert.equal(theme?.kind, "object");

    const importEdge = graph.edges.find(
      (e) =>
        e.source === "file:app/ui/MainScreen.kt"
        && e.target === "file:app/data/User.kt"
        && e.relation === "imports",
    );
    assert.ok(importEdge, "expected jvm import to resolve to file");
    assert.equal(importEdge?.confidence, "EXTRACTED");
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test("java extractor captures classes, methods, and resolves imports", async () => {
  const root = await makeTmp("java");
  try {
    await writeFile(join(root, "package.json"), JSON.stringify({ name: "java-demo" }), "utf8");
    await mkdir(join(root, "src", "com", "app"), { recursive: true });
    await writeFile(
      join(root, "src", "com", "app", "Main.java"),
      [
        "package com.app;",
        "",
        "import com.app.Helper;",
        "",
        "public class Main {",
        "  public static void run() {}",
        "  private int compute(int x) { return x; }",
        "}",
        "",
      ].join("\n"),
      "utf8",
    );
    await writeFile(
      join(root, "src", "com", "app", "Helper.java"),
      ["package com.app;", "", "public class Helper {}", ""].join("\n"),
      "utf8",
    );

    const graph = buildGraph(await scan(root));
    const mainSymbols = graph.fileSymbols["src/com/app/Main.java"] ?? [];
    assert.ok(mainSymbols.find((s) => s.name === "Main" && s.kind === "class"));
    assert.ok(mainSymbols.find((s) => s.name === "Main.run" && s.kind === "method"));
    assert.ok(
      graph.edges.some(
        (e) =>
          e.source === "file:src/com/app/Main.java"
          && e.target === "file:src/com/app/Helper.java"
          && e.relation === "imports",
      ),
    );
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test("swift extractor captures extensions and types", async () => {
  const root = await makeTmp("swift");
  try {
    await writeFile(join(root, "package.json"), JSON.stringify({ name: "ios-demo" }), "utf8");
    await mkdir(join(root, "App"), { recursive: true });
    await writeFile(
      join(root, "App", "Color+Theme.swift"),
      [
        "import SwiftUI",
        "",
        "extension Color: Hashable {",
        "  static let brand = Color.red",
        "  func tinted() -> Color { self }",
        "}",
        "",
        "struct Banner {}",
        "",
        "actor Cache {}",
        "",
      ].join("\n"),
      "utf8",
    );

    const graph = buildGraph(await scan(root));
    const symbols = graph.fileSymbols["App/Color+Theme.swift"] ?? [];
    assert.ok(
      symbols.find((s) => s.kind === "extension" && s.name === "Color: Hashable"),
      "expected swift extension with conformance",
    );
    assert.ok(symbols.find((s) => s.name === "Banner" && s.kind === "class"));
    assert.ok(symbols.find((s) => s.name === "Cache" && s.kind === "class"));
    assert.ok(
      graph.edges.some(
        (e) =>
          e.source === "file:App/Color+Theme.swift"
          && e.target === "external:SwiftUI"
          && e.relation === "imports",
      ),
    );
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test("claude install injects hard rules at top and survives re-runs", async () => {
  const root = await makeTmp("claude");
  try {
    await writeFile(join(root, "CLAUDE.md"), "# Existing Notes\n\nKeep this.\n", "utf8");

    const dryRun = await installClaude({ root, dryRun: true });
    assert.equal(dryRun.changed.length, 2);

    const result = await installClaude({ root });
    assert.equal(result.changed.length, 2);

    const claudeMd = await readFile(join(root, "CLAUDE.md"), "utf8");
    assert.match(claudeMd, /# Existing Notes/);
    assert.match(claudeMd, /HARD RULES/);
    assert.match(claudeMd, /ALWAYS:/);
    assert.match(claudeMd, /NEVER:/);

    const indexOfHeading = claudeMd.indexOf("# Existing Notes");
    const indexOfRules = claudeMd.indexOf("HARD RULES");
    assert.ok(indexOfRules > indexOfHeading, "rules block must appear after the H1 heading");
    const indexOfKeep = claudeMd.indexOf("Keep this");
    assert.ok(indexOfRules < indexOfKeep, "rules block must appear before existing body content");

    const second = await installClaude({ root });
    assert.equal(second.changed.length, 0);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});
