import { posix } from "node:path";
import type { PackageInfo, Skelograph } from "../types.js";
import { flowNameForEntry } from "../flows.js";

export function renderIndex(graph: Skelograph): string {
  const lines: string[] = [];
  const workspace = graph.workspace;
  const projectName = workspace.rootPackageName
    ?? posix.basename(graph.metadata.root.replace(/\\/g, "/"))
    ?? "project";

  lines.push(`# ${projectName}`);
  lines.push("");
  lines.push(`_Generated by skelograph on ${graph.metadata.generatedAt}. Read this file first._`);
  lines.push("");

  lines.push(renderTypeSection(graph));
  lines.push("");

  lines.push("## Where to Look");
  lines.push("");
  lines.push(renderWhereToLook(graph));
  lines.push("");

  if (graph.entryPoints.length > 0) {
    lines.push("## Entry Points");
    lines.push("");
    for (const entry of graph.entryPoints.slice(0, 12)) {
      const pkg = entry.packageName ? ` · \`${entry.packageName}\`` : "";
      lines.push(`- **${entry.label}** — \`${entry.filePath}\`${pkg}`);
    }
    if (graph.entryPoints.length > 12) {
      lines.push(`- …and ${graph.entryPoints.length - 12} more in [ENTRYPOINTS.md](ENTRYPOINTS.md).`);
    }
    lines.push("");
    lines.push(`See [ENTRYPOINTS.md](ENTRYPOINTS.md) for the full list.`);
    lines.push("");
  }

  lines.push("## Packages");
  lines.push("");
  lines.push(renderPackagesTable(graph));
  lines.push("");

  if (graph.svelte.pages.length > 0) {
    lines.push("## Pages");
    lines.push("");
    lines.push(renderPagesSummary(graph));
    lines.push("");
  }

  const featuredFlows = graph.flows.filter((flow) =>
    [
      "sveltekit-server",
      "sveltekit-form-action",
      "next-route",
      "express-app",
      "fastify-app",
      "queue-worker",
      "websocket",
      "sveltekit-hooks",
      "next-middleware",
      "axum-route",
      "rust-main",
    ].includes(flow.entry.kind),
  );
  if (featuredFlows.length > 0) {
    lines.push("## Key Flows");
    lines.push("");
    lines.push("_HTTP endpoints, hooks, workers, and websockets. Page loads live in [FLOWS/](FLOWS/) but aren't featured here._");
    lines.push("");
    for (const flow of featuredFlows.slice(0, 10)) {
      const stepSummary = flow.steps
        .slice(0, 4)
        .map((s) => packageOrFilename(s.filePath, s.packageName))
        .filter((v, i, arr) => arr.indexOf(v) === i)
        .join(" → ");
      lines.push(`- **${flow.title}** — ${stepSummary} ([FLOWS/${flow.name}.md](FLOWS/${flow.name}.md))`);
    }
    if (featuredFlows.length > 10) {
      lines.push(`- …and ${featuredFlows.length - 10} more. Browse [FLOWS/](FLOWS/).`);
    }
    lines.push("");
  } else if (graph.flows.length > 0) {
    lines.push("## Flows");
    lines.push("");
    lines.push(`${graph.flows.length} flow stub${graph.flows.length === 1 ? "" : "s"} in [FLOWS/](FLOWS/).`);
    lines.push("");
  }

  lines.push("## Hotspots");
  lines.push("");
  lines.push("See [HOTSPOTS.md](HOTSPOTS.md) for load-bearing modules and packages.");
  lines.push("");

  lines.push("## Docs");
  lines.push("");
  lines.push("- [MAP.json](MAP.json) — symbol → file lookup (use this instead of grepping for symbol names)");
  lines.push("- [manifest.json](manifest.json) — machine-readable nav index");
  lines.push("");

  return lines.join("\n");
}

function renderTypeSection(graph: Skelograph): string {
  const workspace = graph.workspace;
  const frameworks = new Set(
    graph.workspace.packages
      .map((pkg) => pkg.framework)
      .filter((f): f is NonNullable<typeof f> => Boolean(f) && f !== "unknown"),
  );
  const languages = graph.stats.languages;
  const primaryLanguage = detectPrimaryLanguage(languages);
  const frameworkList = [...frameworks].join(" + ") || primaryLanguage;

  const typeLabel = (() => {
    switch (workspace.kind) {
      case "pnpm":
        return `pnpm workspace monorepo (${frameworkList})`;
      case "npm":
        return `npm workspace monorepo (${frameworkList})`;
      case "yarn":
        return `yarn workspace monorepo (${frameworkList})`;
      case "turborepo-hinted":
        return `Turborepo-hinted monorepo (${frameworkList})`;
      case "cargo":
        return `Cargo workspace (${frameworkList})`;
      default:
        return `single-package ${frameworkList} project`;
    }
  })();

  const warning = languages["rust"] && !graph.workspace.packages.length
    ? "\n\n_Rust files detected but no Cargo workspace found. Check that `Cargo.toml` exists at the project root._"
    : "";

  return `## Type\n\n${typeLabel}${warning}`;
}

function detectPrimaryLanguage(counts: Record<string, number>): string {
  const entries = Object.entries(counts).sort((a, b) => b[1] - a[1]);
  if (entries.length === 0) return "TypeScript / JavaScript";
  const [name] = entries[0];
  switch (name) {
    case "rust":
      return "Rust";
    case "typescript":
    case "javascript":
    case "svelte":
      return "TypeScript / JavaScript";
    case "python":
      return "Python";
    case "go":
      return "Go";
    default:
      return name;
  }
}

function renderWhereToLook(graph: Skelograph): string {
  const rows: Array<[string, string]> = [];
  const isCargo = graph.workspace.kind === "cargo";
  const bare = (name: string) => name.replace(/^@[^/]+\//, "");

  const authPackage =
    graph.workspace.packages.find((pkg) => /^auth$/i.test(bare(pkg.name)))
    ?? graph.workspace.packages.find((pkg) => /(^|[_/-])(auth|session|jwt|identity)([_/-]|$)/i.test(bare(pkg.name)));
  if (authPackage) {
    rows.push(["Anything involving login / sessions / JWT", packageLink(authPackage)]);
  }

  const dbPackage = graph.workspace.packages.find((pkg) => /(^|[_/-])(db|database|prisma|drizzle|sqlx)([_/-]|$)/i.test(bare(pkg.name)));
  if (dbPackage) {
    rows.push(["Database schema / migrations", packageLink(dbPackage)]);
  }

  const paymentsPackage = graph.workspace.packages.find((pkg) => /(pay|billing|stripe|checkout|invoice)/i.test(bare(pkg.name)));
  if (paymentsPackage) {
    rows.push(["Payments / billing / checkout", packageLink(paymentsPackage)]);
  }

  if (isCargo) {
    const apiCrates = graph.workspace.packages.filter((pkg) => /_api$/.test(pkg.name));
    if (apiCrates.length > 0) {
      rows.push([
        "Adding / changing an HTTP endpoint",
        apiCrates.map(packageLink).slice(0, 3).join(" · "),
      ]);
    }
    const kernelPackage =
      graph.workspace.packages.find((pkg) => /(^|[_/-])(kernel)([_/-]|$)/i.test(pkg.name))
      ?? graph.workspace.packages.find((pkg) => /(^|[_/-])(core|common)([_/-]|$)/i.test(pkg.name));
    if (kernelPackage) {
      rows.push(["Shared types / app config / error envelope", packageLink(kernelPackage)]);
    }
    const busPackage = graph.workspace.packages.find((pkg) => /(^|[_/-])(bus|events?|nats|mq|queue)([_/-]|$)/i.test(pkg.name));
    if (busPackage) {
      rows.push(["Events / message bus / async jobs", packageLink(busPackage)]);
    }
  } else {
    const webPackage = graph.workspace.packages.find((pkg) => /^web|front|client|app/i.test(bare(pkg.name)));
    if (webPackage) {
      rows.push(["Adding a new HTTP endpoint", `${packageLink(webPackage)} § Routes`]);
    }
  }

  const firstCheckoutFlow = graph.flows.find((flow) => /checkout|order|purchase/i.test(flow.name));
  if (firstCheckoutFlow) {
    rows.push(["Checkout / order lifecycle", flowLink(firstCheckoutFlow.name)]);
  }

  const firstAuthFlow = graph.flows.find((flow) => /(?:^|_)(login|signin|signup|register)(?:_|$)/i.test(flow.name));
  if (firstAuthFlow) {
    rows.push(["Login / authentication flow", flowLink(firstAuthFlow.name)]);
  }

  const queueFlow = graph.flows.find((flow) => flow.entry.kind === "queue-worker");
  if (queueFlow) {
    rows.push(["Background jobs / queues", flowLink(queueFlow.name)]);
  }

  const wsFlow = graph.flows.find((flow) => flow.entry.kind === "websocket");
  if (wsFlow) {
    rows.push(["WebSocket / realtime", flowLink(wsFlow.name)]);
  }

  if (graph.flows.length > 0) {
    rows.push(["Error / HTTP status debugging", flowLink(graph.flows[0].name) + " § Decision Points"]);
  }

  rows.push(["Where a specific symbol is defined", "[MAP.json](MAP.json) (do NOT grep)"]);
  rows.push(["What the load-bearing modules are", "[HOTSPOTS.md](HOTSPOTS.md)"]);
  rows.push(["Every execution start", "[ENTRYPOINTS.md](ENTRYPOINTS.md)"]);

  const header = "| Task | Go to |";
  const sep = "|------|-------|";
  const body = rows.map(([task, target]) => `| ${task} | ${target} |`).join("\n");
  return [header, sep, body].join("\n");
}

function renderPackagesTable(graph: Skelograph): string {
  if (graph.workspace.packages.length === 0) {
    return "_No packages detected._";
  }
  const header = "| Package | Purpose | Page |";
  const sep = "|---------|---------|------|";
  const rows = graph.workspace.packages.map((pkg) => {
    const purpose = pkg.description?.trim() || "_(no description)_";
    return `| \`${pkg.name}\` | ${purpose} | [${pkg.relativePath}](PACKAGES/${packageFileName(pkg)}.md) |`;
  });
  return [header, sep, ...rows].join("\n");
}

function packageLink(pkg: PackageInfo): string {
  return `[PACKAGES/${packageFileName(pkg)}.md](PACKAGES/${packageFileName(pkg)}.md)`;
}

function flowLink(name: string): string {
  return `[FLOWS/${name}.md](FLOWS/${name}.md)`;
}

export function packageFileName(pkg: PackageInfo): string {
  return pkg.name.replace(/^@/, "").replace(/[^a-z0-9_-]+/gi, "_");
}

function renderPagesSummary(graph: Skelograph): string {
  const pagesByPackage = new Map<string, number>();
  const pagesWithActions = new Map<string, number>();
  const pagesWithFetch = new Map<string, number>();
  for (const page of graph.svelte.pages) {
    const key = page.packageName ?? "(root)";
    pagesByPackage.set(key, (pagesByPackage.get(key) ?? 0) + 1);
    if (page.hasActions) pagesWithActions.set(key, (pagesWithActions.get(key) ?? 0) + 1);
    if (page.fetchCalls.length > 0) pagesWithFetch.set(key, (pagesWithFetch.get(key) ?? 0) + 1);
  }
  const rows: string[] = [];
  rows.push(`Detected **${graph.svelte.pages.length}** SvelteKit page${graph.svelte.pages.length === 1 ? "" : "s"}. Breakdown:`);
  rows.push("");
  rows.push("| Package | Pages | With actions | With fetch() |");
  rows.push("|---------|-------|--------------|--------------|");
  for (const [pkg, count] of [...pagesByPackage.entries()].sort((a, b) => b[1] - a[1])) {
    const pageRef = graph.workspace.packages.find((p) => p.name === pkg);
    const link = pageRef ? `[\`${pkg}\`](PACKAGES/${pkg.replace(/^@/, "").replace(/[^a-z0-9_-]+/gi, "_")}.md#pages)` : `\`${pkg}\``;
    rows.push(`| ${link} | ${count} | ${pagesWithActions.get(pkg) ?? 0} | ${pagesWithFetch.get(pkg) ?? 0} |`);
  }
  const apiEndpoints = Object.keys(graph.svelte.apiCallers).length;
  if (apiEndpoints > 0) {
    rows.push("");
    rows.push(`Frontend pages call **${apiEndpoints}** distinct API endpoint${apiEndpoints === 1 ? "" : "s"}. See per-endpoint FLOWS/ files for the reverse lookup ("Called by page:").`);
  }
  return rows.join("\n");
}

function packageOrFilename(filePath: string, packageName?: string): string {
  if (packageName) return packageName;
  const base = filePath.split("/").slice(-2).join("/");
  return base;
}

export { flowNameForEntry };
